server:
  port: 8761
spring:
  application:
    name: discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 30000
management:
  endpoints.web.exposure.include: '*'