server:
  port: 8082
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: question-service
  datasource:
    url: jdbc:mysql://localhost:3307/certpilot?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: app
    password: apppw
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.flywaydb: DEBUG
