server:
  port: 8082
  error:
    include-message: always
    include-stacktrace: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/certpilot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: app
    password: apppw
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.format_sql: true

  flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true


management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springdoc: DEBUG
