-- LearningSession mode 컬럼 길이 확장
-- ASSIST_PRACTICAL_DIFFICULTY (27자), ASSIST_WRITTEN_DIFFICULTY (25자) 등을 수용하기 위해 확장

ALTER TABLE learning_session
  MODIFY COLUMN mode VARCHAR(50) NOT NULL COMMENT 'WRITTEN | PRACTICAL | REVIEW | ASSIST_PRACTICAL_DIFFICULTY | ASSIST_WRITTEN_DIFFICULTY';

-- StudySession mode 컬럼을 ENUM에서 VARCHAR로 변경
-- ASSIST_PRACTICAL_DIFFICULTY (27자), ASSIST_WRITTEN_DIFFICULTY (25자) 등을 수용하기 위해 변경

ALTER TABLE study_session
  MODIFY COLUMN mode VARCHAR(50) NOT NULL COMMENT 'MICRO | REVIEW | ASSIST_CATEGORY | ASSIST_DIFFICULTY | ASSIST_WEAK | ASSIST_PRACTICAL_DIFFICULTY | ASSIST_WRITTEN_DIFFICULTY';

