server:
  port: 8083
  server:
    error:
      include-message: always
      include-binding-errors: always
      whitelabel:
        enabled: false

  logging:
    level:
      com.OhRyue.certpilot.learn.client: DEBUG
      org.springframework.cloud.openfeign: DEBUG
      feign: DEBUG

spring:
  application:
    name: learn-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: basic

