server:
  port: 8083

logging:
  level:
    com.OhRyue.certpilot.learn.client: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG

spring:
  application:
    name: learn-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
      httpclient:
        hc5:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    non-secure-port: 8083
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${server.port}:${HOSTNAME}

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: basic

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      questionApi:
        baseConfig: default
  retry:
    instances:
      questionApi:
        maxAttempts: 3
        waitDuration: 300ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - feign.RetryableException
  timelimiter:
    instances:
      questionApi:
        timeoutDuration: 3s
        cancelRunningFuture: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: never
