server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/api/questions/**
        - id: learn-service
          uri: lb://learn-service
          predicates:
            - Path=/api/learn/**
        - id: certs-service
          uri: lb://certs-service
          predicates:
            - Path=/api/certs/**
        - id: calendar-service
          uri: lb://calendar-service
          predicates:
            - Path=/api/calendar/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: curriculum-service
          uri: lb://curriculum-service
          predicates:
            - Path=/api/curriculum/**
        - id: ability-service
          uri: lb://ability-service
          predicates:
            - Path=/api/ability/**
        - id: wrongnote-service
          uri: lb://wrongnote-service
          predicates:
            - Path=/api/wrongnote/**
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/api/quiz/**
        - id: auxiliary-service
          uri: lb://auxiliary-service
          predicates:
            - Path=/api/auxiliary/**
        - id: progress-service
          uri: lb://progress-service
          predicates:
            - Path=/api/progress/**
        - id: recommend-service
          uri: lb://recommend-service
          predicates:
            - Path=/api/recommend/**
        - id: result-service
          uri: lb://result-service
          predicates:
            - Path=/api/result/**
      default-filters: [ ]

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    non-secure-port: 8080
    instance-id: ${spring.application.name}:${server.port}:${HOSTNAME}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway
  endpoint:
    gateway:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.cloud.gateway: INFO
