DROP TABLE IF EXISTS users_auth;

CREATE TABLE users_auth (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,  -- 로그인 ID
  email VARCHAR(255) NOT NULL UNIQUE,     -- 이메일(인증용)
  password VARCHAR(255) NOT NULL,         -- 암호화 PW
  role VARCHAR(50) NOT NULL DEFAULT 'USER',
  enabled BOOLEAN NOT NULL DEFAULT FALSE, -- 이메일 인증 여부
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);