SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE leaderboard_snapshot
  MODIFY COLUMN scope ENUM('OVERALL','WEEKLY','HALL_OF_FAME','FRIENDS') NOT NULL DEFAULT 'OVERALL';

UPDATE leaderboard_snapshot
SET scope = 'OVERALL'
WHERE scope = 'GLOBAL';

SET FOREIGN_KEY_CHECKS = 1;

